#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif

uint16_t get_quick_tap_term(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case LT(3,KC_F):
            return 0;
        default:
            return QUICK_TAP_TERM;
    }
}

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x5_2(
        KC_Q, KC_W, KC_E, KC_R, KC_T,
        KC_Y, KC_U, KC_I, KC_O, KC_P,
        LSFT_T(KC_A), LT(5,KC_S), LT(1,KC_D), LT(3,KC_F), C_S_T(KC_G),
        C_S_T(KC_H), LT(4,KC_J), LT(2,KC_K), LT(6,KC_L), LSFT_T(KC_SCLN),
        LT(8,KC_Z), LCTL_T(KC_X), LALT_T(KC_C), LGUI_T(KC_V), LCA_T(KC_B),
        LCA_T(KC_N), LGUI_T(KC_M), LALT_T(KC_COMM), LCTL_T(KC_DOT), LT(8,KC_SLSH),
        KC_DEL, LT(7,KC_SPC), KC_BSPC, KC_ENT
    ),
    [1] = LAYOUT_split_3x5_2(
        _______, _______, _______, _______, _______,
        KC_PGUP, KC_LCBR, KC_LT, KC_GT, KC_RCBR,
        KC_HOME, _______, KC_NO, _______, _______,
        KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_END,
        _______, _______, _______, _______, _______,
        KC_PGDN, KC_LBRC, KC_LPRN, KC_RPRN, KC_RBRC,
        _______, _______, _______, _______
    ),
    [2] = LAYOUT_split_3x5_2(
        _______, _______, KC_PGUP, _______, _______,
        _______, _______, _______, _______, _______,
        KC_LEFT, KC_UP, KC_DOWN, KC_RGHT, _______,
        _______, KC_LGUI, KC_NO, LCTL(KC_LALT), LCA(KC_LSFT),
        _______, KC_HOME, KC_PGDN, KC_END, _______,
        _______, _______, _______, _______, _______,
        _______, _______, _______, _______
    ),
    [3] = LAYOUT_split_3x5_2(
        _______, _______, _______, _______, _______,
        KC_EQL, KC_UNDS, KC_PIPE, KC_QUOT, KC_AT,
        KC_CIRC, KC_ASTR, KC_AMPR, KC_NO, _______,
        KC_HASH, KC_TILD, KC_SLSH, KC_DQUO, KC_DLR,
        _______, _______, _______, _______, _______,
        KC_PERC, KC_MINS, KC_BSLS, KC_GRV, KC_EXLM,
        RGB_RMOD, _______, _______, RGB_MOD
    ),
    [4] = LAYOUT_split_3x5_2(
        _______, KC_COLN, KC_LT, KC_GT, KC_SCLN,
        _______, _______, KC_MINS, _______, _______,
        KC_LCBR, KC_RCBR, KC_LPRN, KC_RPRN, KC_AT,
        _______, KC_NO, KC_EQL, KC_PLUS, KC_PERC,
        _______, KC_EXLM, KC_LBRC, KC_RBRC, _______,
        _______, _______, _______, _______, _______,
        KC_VOLD, _______, _______, KC_VOLU
    ),
    [5] = LAYOUT_split_3x5_2(
        _______, _______, _______, _______, KC_CAPS,
        _______, KC_F7, KC_F8, KC_F9, KC_F10,
        _______, KC_NO, LCTL(KC_LALT), KC_DEL, KC_NUM,
        _______, KC_F1, KC_F2, KC_F3, KC_F11,
        _______, _______, _______, _______, _______,
        _______, KC_F4, KC_F5, KC_F6, KC_F12,
        _______, _______, _______, _______
    ),
    [6] = LAYOUT_split_3x5_2(
        KC_SLSH, KC_7, KC_8, KC_9, KC_PLUS,
        KC_CIRC, _______, _______, _______, _______,
        KC_0, KC_1, KC_2, KC_3, KC_MINS,
        KC_COMM, KC_DOT, KC_COLN, KC_NO, _______,
        KC_ASTR, KC_4, KC_5, KC_6, KC_EQL,
        KC_PERC, _______, _______, _______, _______,
        _______, _______, _______, _______
    ),
    [7] = LAYOUT_split_3x5_2(
        KC_ESC, KC_NUM, KC_COLN, KC_ESC, _______,
        KC_MUTE, KC_VOLD, KC_VOLU, _______, KC_PSCR,
        _______, KC_PERC, KC_SLSH, KC_ENT, _______,
        KC_MEDIA_PLAY_PAUSE, KC_MEDIA_NEXT_TRACK, KC_MEDIA_PREV_TRACK, _______, _______,
        KC_DEL, _______, _______, KC_EXLM, _______,
        DF(0), _______, RALT_T(KC_COMM), RCTL_T(KC_DOT), _______,
        _______, KC_NO, KC_TAB, KC_DEL
    ),
    [8] = LAYOUT_split_3x5_2(
        _______, _______, KC_SCLN, _______, QK_BOOT,
        _______, KC_RBRC, KC_GRV, KC_EQL, _______,
        LSFT_T(KC_QUOT), _______, _______, _______, _______,
        _______, KC_MINS, _______, KC_0, KC_RSFT,
        KC_NO, _______, _______, _______, _______,
        _______, KC_BSLS, _______, KC_LBRC, KC_NO,
        _______, _______, _______, _______
    )
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)




